import { Scheme, Language } from '../types';

export const DUMMY_SCHEMES: Scheme[] = [
    {
        id: 'pmjdy',
        icon: 'users',
        name: {
            [Language.EN]: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
            [Language.HI]: 'प्रधानमंत्री जन धन योजना (पीएमजेडीवाई)',
            [Language.TE]: 'ప్రధాన మంత్రి జన్ ధన్ యోజన (పిఎంజెడివై)',
        },
        description: {
            [Language.EN]: 'A national mission on financial inclusion to ensure access to financial services in an affordable manner.',
            [Language.HI]: 'वित्तीय समावेशन पर एक राष्ट्रीय मिशन जो सस्ती तरीके से वित्तीय सेवाओं तक पहुंच सुनिश्चित करता है।',
            [Language.TE]: 'ఆర్థిక సేవలకు సరసమైన రీతిలో ప్రాప్యతను నిర్ధారించడానికి ఆర్థిక చేర్పుపై జాతీయ మిషన్.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 65,
            maxIncome: 1000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen', 'Farmer', 'Job Seeker'],
        },
        benefits: {
            [Language.EN]: ['Zero balance bank account', 'Accidental insurance cover of Rs. 1 lakh', 'Overdraft facility up to Rs. 10,000'],
            [Language.HI]: ['शून्य शेष बैंक खाता', '1 लाख रुपये का दुर्घटना बीमा कवर', '10,000 रुपये तक की ओवरड्राफ्ट सुविधा'],
            [Language.TE]: ['జీరో బ్యాలెన్స్ బ్యాంక్ ఖాతా', 'రూ. 1 లక్ష ప్రమాద బీమా కవర్', 'రూ. 10,000 వరకు ఓవర్‌డ్రాఫ్ట్ సౌకర్యం'],
        },
        documents: {
            [Language.EN]: ['Aadhaar Card', 'PAN Card', 'Passport size photo'],
            [Language.HI]: ['आधार कार्ड', 'पैन कार्ड', 'पासपोर्ट साइज फोटो'],
            [Language.TE]: ['ఆధార్ కార్డ్', 'పాన్ కార్డ్', 'పాస్‌పోర్ట్ సైజు ఫోటో'],
        },
        applyLink: 'https://www.pmjdy.gov.in/',
    },
    {
        id: 'kcc',
        icon: 'leaf',
        name: {
            [Language.EN]: 'Kisan Credit Card (KCC)',
            [Language.HI]: 'किसान क्रेडिट कार्ड (केसीसी)',
            [Language.TE]: 'కిసాన్ క్రెడిట్ కార్డ్ (కెసిసి)',
        },
        description: {
            [Language.EN]: 'Provides farmers with timely access to credit for their cultivation needs in a simple and hassle-free way.',
            [Language.HI]: 'किसानों को उनकी खेती की जरूरतों के लिए एक सरल और परेशानी मुक्त तरीके से समय पर ऋण उपलब्ध कराता है।',
            [Language.TE]: 'రైతులకు వారి సాగు అవసరాలకు సరళమైన మరియు అవాంతరాలు లేని విధంగా సకాలంలో క్రెడిట్ అందిస్తుంది.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 75,
            maxIncome: 2000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Farmer'],
        },
        benefits: {
            [Language.EN]: ['Short-term credit for cultivation', 'Post-harvest expenses', 'Consumption requirements of farmer household'],
            [Language.HI]: ['खेती के लिए अल्पकालिक ऋण', 'फसल कटाई के बाद के खर्चे', 'किसान परिवार की उपभोग आवश्यकताएं'],
            [Language.TE]: ['సాగు కోసం స్వల్పకాలిక రుణం', 'పంటకోత అనంతర ఖర్చులు', 'రైతు కుటుంబ వినియోగ అవసరాలు'],
        },
        documents: {
            [Language.EN]: ['Land documents', 'Aadhaar Card', 'PAN Card'],
            [Language.HI]: ['भूमि दस्तावेज', 'आधार कार्ड', 'पैन कार्ड'],
            [Language.TE]: ['భూమి పత్రాలు', 'ఆధార్ కార్డ్', 'పాన్ కార్డ్'],
        },
        applyLink: 'https://www.sbi.co.in/web/agri-rural/agriculture-banking/crop-finance/kisan-credit-card',
    },
    {
        id: 'tsfr',
        icon: 'academic-cap',
        name: {
            [Language.EN]: 'Telangana State Fee Reimbursement',
            [Language.HI]: 'तेलंगाना राज्य शुल्क प्रतिपूर्ति',
            [Language.TE]: 'తెలంగాణ రాష్ట్ర ఫీజు రీయింబర్స్‌మెంట్',
        },
        description: {
            [Language.EN]: 'Offers financial assistance to students from economically weaker sections for pursuing post-matriculation courses.',
            [Language.HI]: 'पोस्ट-मैट्रिक पाठ्यक्रम करने के लिए आर्थिक रूप से कमजोर वर्गों के छात्रों को वित्तीय सहायता प्रदान करता है।',
            [Language.TE]: 'పోస్ట్-మెట్రికుల్యూషన్ కోర్సులను అభ్యసించడానికి ఆర్థికంగా బలహీన వర్గాల విద్యార్థులకు ఆర్థిక సహాయం అందిస్తుంది.',
        },
        eligibility: {
            minAge: 16,
            maxAge: 30,
            maxIncome: 250000,
            states: ['Telangana'],
            categories: ['SC', 'ST', 'OBC', 'EWS'],
            roles: ['Student'],
        },
        benefits: {
            [Language.EN]: ['Full fee reimbursement for eligible students in professional courses', 'Maintenance charges for hostel students'],
            [Language.HI]: ['पेशेवर पाठ्यक्रमों में पात्र छात्रों के लिए पूर्ण शुल्क प्रतिपूर्ति', 'छात्रावास के छात्रों के लिए रखरखाव शुल्क'],
            [Language.TE]: ['వృత్తి విద్యా కోర్సులలో అర్హులైన విద్యార్థులకు పూర్తి ఫీజు రీయింబర్స్‌మెంట్', 'హాస్టల్ విద్యార్థులకు నిర్వహణ ఛార్జీలు'],
        },
        documents: {
            [Language.EN]: ['Caste Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card'],
            [Language.HI]: ['जाति प्रमाण पत्र', 'आय प्रमाण पत्र', 'वास्तविक प्रमाण पत्र', 'आधार कार्ड'],
            [Language.TE]: ['కుల ధృవీకరణ పత్రం', 'ఆదాయ ధృవీకరణ పత్రం', 'బోనఫైడ్ సర్టిఫికేట్', 'ఆధార్ కార్డ్'],
        },
        applyLink: 'https://telanganaepass.cgg.gov.in/',
    },
    {
        id: 'startupindia',
        icon: 'light-bulb',
        name: {
            [Language.EN]: 'Startup India Seed Fund Scheme',
            [Language.HI]: 'स्टार्टअप इंडिया सीड फंड योजना',
            [Language.TE]: 'స్టార్టప్ ఇండియా సీడ్ ఫండ్ స్కీమ్',
        },
        description: {
            [Language.EN]: 'Aims to build a strong eco-system for nurturing innovation and Startups that will drive sustainable economic growth.',
            [Language.HI]: 'नवाचार और स्टार्टअप को बढ़ावा देने के लिए एक मजबूत पारिस्थितिकी तंत्र बनाने का लक्ष्य है जो स्थायी आर्थिक विकास को बढ़ावा देगा।',
            [Language.TE]: 'స్థిరమైన ఆర్థిక వృద్ధిని నడిపించే ఆవిష్కరణలు మరియు స్టార్టప్‌లను ప్రోత్సహించడానికి ఒక బలమైన పర్యావరణ వ్యవస్థను నిర్మించడం లక్ష్యం.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 100,
            maxIncome: 10000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Entrepreneur'],
        },
        benefits: {
            [Language.EN]: ['Financial assistance to startups for proof of concept', 'Prototype development', 'Product trials', 'Market entry'],
            [Language.HI]: ['अवधारणा के प्रमाण के लिए स्टार्टअप को वित्तीय सहायता', 'प्रोटोटाइप विकास', 'उत्पाद परीक्षण', 'बाजार में प्रवेश'],
            [Language.TE]: ['భావన యొక్క రుజువు కోసం స్టార్టప్‌లకు ఆర్థిక సహాయం', 'ప్రోటోటైప్ అభివృద్ధి', 'ఉత్పత్తి పరీక్షలు', 'మార్కెట్ ప్రవేశం'],
        },
        documents: {
            [Language.EN]: ['Startup Recognition Certificate', 'Business Plan', 'Company Incorporation documents'],
            [Language.HI]: ['स्टार्टअप मान्यता प्रमाणपत्र', 'व्यापार योजना', 'कंपनी निगमन दस्तावेज'],
            [Language.TE]: ['స్టార్టప్ గుర్తింపు సర్టిఫికేట్', 'వ్యాపార ప్రణాళిక', 'కంపెనీ ఇన్కార్పొరేషన్ పత్రాలు'],
        },
        applyLink: 'https://www.startupindia.gov.in/content/sih/en/funding/seed-fund-scheme.html',
    },
    {
        id: 'pmay-u',
        icon: 'home',
        name: {
            [Language.EN]: 'Pradhan Mantri Awas Yojana (Urban) - PMAY(U)',
            [Language.HI]: 'प्रधानमंत्री आवास योजना (शहरी) - पीएमएवाई (यू)',
            [Language.TE]: 'ప్రధాన మంత్రి ఆవాస్ యోజన (పట్టణ) - పిఎంఎవై(యు)',
        },
        description: {
            [Language.EN]: 'A mission to provide "Housing for All" in urban areas. The scheme provides central assistance to implementing agencies through States/Union Territories.',
            [Language.HI]: 'शहरी क्षेत्रों में "सभी के लिए आवास" प्रदान करने का एक मिशन। यह योजना राज्यों/केंद्र शासित प्रदेशों के माध्यम से कार्यान्वयन एजेंसियों को केंद्रीय सहायता प्रदान करती है।',
            [Language.TE]: 'పట్టణ ప్రాంతాల్లో "అందరికీ ఇళ్లు" అందించే లక్ష్యం. ఈ పథకం రాష్ట్రాలు/కేంద్రపాలిత ప్రాంతాల ద్వారా అమలు చేసే ఏజెన్సీలకు కేంద్ర సహాయం అందిస్తుంది.',
        },
        eligibility: {
            minAge: 21,
            maxAge: 70,
            maxIncome: 600000,
            states: ['Pan-India'],
            categories: ['General', 'EWS', 'OBC', 'SC', 'ST'],
            roles: ['Citizen', 'Job Seeker'],
            genders: ['Female', 'Male', 'Other'],
        },
        benefits: {
            [Language.EN]: ['Credit Linked Subsidy Scheme (CLSS)', 'Affordable housing in partnership', 'In-situ slum redevelopment'],
            [Language.HI]: ['क्रेडिट लिंक्ड सब्सिडी योजना (सीएलएसएस)', 'साझेदारी में किफायती आवास', 'इन-सीटू स्लम पुनर्विकास'],
            [Language.TE]: ['క్రెడిట్ లింక్డ్ సబ్సిడీ స్కీమ్ (సిఎల్‌ఎస్‌ఎస్)', 'భాగస్వామ్యంతో సరసమైన గృహాలు', 'ఇన్-సిటు స్లమ్ పునరాభివృద్ధి'],
        },
        documents: {
            [Language.EN]: ['Aadhaar Card', 'PAN Card', 'Income Certificate', 'Proof of Residence'],
            [Language.HI]: ['आधार कार्ड', 'पैन कार्ड', 'आय प्रमाण पत्र', 'निवास का प्रमाण'],
            [Language.TE]: ['ఆధార్ కార్డ్', 'పాన్ కార్డ్', 'ఆదాయ ధృవీకరణ పత్రం', 'నివాస రుజువు'],
        },
        applyLink: 'https://pmay-urban.gov.in/',
    },
    {
        id: 'bbbp',
        icon: 'users',
        name: {
            [Language.EN]: 'Beti Bachao, Beti Padhao Scheme',
            [Language.HI]: 'बेटी बचाओ, बेटी पढ़ाओ योजना',
            [Language.TE]: 'బేటీ బచావో, బేటీ పఢావో పథకం',
        },
        description: {
            [Language.EN]: 'Aims to address the declining Child Sex Ratio (CSR) and related issues of women empowerment over a life-cycle continuum.',
            [Language.HI]: 'इसका उद्देश्य गिरते बाल लिंगानुपात (सीएसआर) और जीवन-चक्र की निरंतरता पर महिला सशक्तिकरण के संबंधित मुद्दों को संबोधित करना है।',
            [Language.TE]: 'క్షీణిస్తున్న బాలల లింగ నిష్పత్తి (సిఎస్‌ఆర్) మరియు జీవితకాల కొనసాగింపులో మహిళా సాధికారతకు సంబంధించిన సమస్యలను పరిష్కరించడం దీని లక్ష్యం.',
        },
        eligibility: {
            minAge: 0,
            maxAge: 10,
            maxIncome: 10000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen'],
            genders: ['Female'],
        },
        benefits: {
            [Language.EN]: ['Prevention of gender-biased sex selective elimination', 'Ensuring survival & protection of the girl child', 'Ensuring education of the girl child'],
            [Language.HI]: ['लिंग-पक्षपाती लिंग चयनात्मक उन्मूलन की रोकथाम', 'बालिका का अस्तित्व और सुरक्षा सुनिश्चित करना', 'बालिका की शिक्षा सुनिश्चित करना'],
            [Language.TE]: ['లింగ-పక్షపాత లింగ ఎంపిక తొలగింపును నివారించడం', 'బాలిక మనుగడ & రక్షణను నిర్ధారించడం', 'బాలిక విద్యను నిర్ధారించడం'],
        },
        documents: {
            [Language.EN]: ["Birth certificate of girl child", "Parent's identity proof", "Address proof"],
            [Language.HI]: ['बालिका का जन्म प्रमाण पत्र', 'माता-पिता का पहचान प्रमाण', 'पते का प्रमाण'],
            [Language.TE]: ['బాలిక జనన ధృవీకరణ పత్రం', 'తల్లిదండ్రుల గుర్తింపు రుజువు', 'చిరునామా రుజువు'],
        },
        applyLink: 'https://wcd.nic.in/bbbp-schemes',
    },
    {
        id: 'apy',
        icon: 'users',
        name: {
            [Language.EN]: 'Atal Pension Yojana (APY)',
            [Language.HI]: 'अटल पेंशन योजना (एपीवाई)',
            [Language.TE]: 'అటల్ పెన్షన్ యోజన (ఎపివై)',
        },
        description: {
            [Language.EN]: 'A government-backed pension scheme in India, targeted at the unorganized sector.',
            [Language.HI]: 'भारत में एक सरकार समर्थित पेंशन योजना, जो असंगठित क्षेत्र पर लक्षित है।',
            [Language.TE]: 'భారతదేశంలో ప్రభుత్వ-మద్దతుగల పెన్షన్ పథకం, అసంఘటిత రంగాన్ని లక్ష్యంగా చేసుకుంది.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 40,
            maxIncome: 2500000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen', 'Job Seeker', 'Farmer', 'Entrepreneur'],
        },
        benefits: {
            [Language.EN]: ['Fixed pension from Rs. 1,000 to Rs. 5,000 per month', 'Guaranteed pension benefits', 'Government co-contribution for eligible subscribers'],
            [Language.HI]: ['1,000 रुपये से 5,000 रुपये प्रति माह तक की निश्चित पेंशन', 'गारंटीकृत पेंशन लाभ', 'योग्य ग्राहकों के लिए सरकारी सह-योगदान'],
            [Language.TE]: ['నెలకు రూ. 1,000 నుండి రూ. 5,000 వరకు స్థిర పెన్షన్', 'హామీతో కూడిన పెన్షన్ ప్రయోజనాలు', 'అర్హులైన చందాదారులకు ప్రభుత్వ సహ-కంట్రిబ్యూషన్'],
        },
        documents: {
            [Language.EN]: ['Bank Account', 'Aadhaar Card', 'Mobile Number'],
            [Language.HI]: ['बैंक खाता', 'आधार कार्ड', 'मोबाइल नंबर'],
            [Language.TE]: ['బ్యాంక్ ఖాతా', 'ఆధార్ కార్డ్', 'మొబైల్ నంబర్'],
        },
        applyLink: 'https://www.npscra.nsdl.co.in/apply-for-apy.php',
    },
    {
        id: 'pmkvy',
        icon: 'briefcase',
        name: {
            [Language.EN]: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
            [Language.HI]: 'प्रधानमंत्री कौशल विकास योजना (पीएमकेवीवाई)',
            [Language.TE]: 'ప్రధాన మంత్రి కౌశల్ వికాస్ యోజన (పిఎంకెవివై)',
        },
        description: {
            [Language.EN]: 'A skill development initiative scheme of the Government of India for recognition and standardization of skills.',
            [Language.HI]: 'कौशल की मान्यता और मानकीकरण के लिए भारत सरकार की एक कौशल विकास पहल योजना।',
            [Language.TE]: 'నైపుణ్యాల గుర్తింపు మరియు ప్రామాణీకరణ కోసం భారత ప్రభుత్వం యొక్క నైపుణ్యాభివృద్ధి కార్యక్రమం.',
        },
        eligibility: {
            minAge: 15,
            maxAge: 45,
            maxIncome: 10000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Job Seeker', 'Student'],
        },
        benefits: {
            [Language.EN]: ['Free skill training and certification', 'Monetary reward upon successful certification', 'Placement assistance'],
            [Language.HI]: ['मुफ्त कौशल प्रशिक्षण और प्रमाणन', 'सफल प्रमाणन पर मौद्रिक इनाम', 'प्लेसमेंट सहायता'],
            [Language.TE]: ['ఉచిత నైపుణ్య శిక్షణ మరియు ధృవీకరణ', 'విజయవంతమైన ధృవీకరణపై ద్రవ్య బహుమతి', 'ఉద్యోగ సహాయం'],
        },
        documents: {
            [Language.EN]: ['Aadhaar Card', 'Bank account details', 'Two passport size photos'],
            [Language.HI]: ['आधार कार्ड', 'बैंक खाते का विवरण', 'दो पासपोर्ट साइज फोटो'],
            [Language.TE]: ['ఆధార్ కార్డ్', 'బ్యాంక్ ఖాతా వివరాలు', 'రెండు పాస్‌పోర్ట్ సైజు ఫోటోలు'],
        },
        applyLink: 'https://www.pmkvyofficial.org/',
    },
    {
        id: 'mmysy-up',
        icon: 'light-bulb',
        name: {
            [Language.EN]: 'Mukhya Mantri Yuva Swarozgar Yojana (Uttar Pradesh)',
            [Language.HI]: 'मुख्यमंत्री युवा स्वरोजगार योजना (उत्तर प्रदेश)',
            [Language.TE]: 'ముఖ్య మంత్రి యువ స్వరోజ్‌గార్ యోజన (ఉత్తర ప్రదేశ్)',
        },
        description: {
            [Language.EN]: 'Provides financial assistance to unemployed educated youth in Uttar Pradesh to set up their own industry or service business.',
            [Language.HI]: 'उत्तर प्रदेश में बेरोजगार शिक्षित युवाओं को अपना उद्योग या सेवा व्यवसाय स्थापित करने के लिए वित्तीय सहायता प्रदान करता है।',
            [Language.TE]: 'ఉత్తర ప్రదేశ్‌లో నిరుద్యోగ విద్యావంతులైన యువత వారి స్వంత పరిశ్రమ లేదా సేవా వ్యాపారాన్ని స్థాపించడానికి ఆర్థిక సహాయం అందిస్తుంది.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 40,
            maxIncome: 500000,
            states: ['Uttar Pradesh'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Entrepreneur', 'Job Seeker'],
        },
        benefits: {
            [Language.EN]: ['Loan up to ₹25 lakh for industries', 'Loan up to ₹10 lakh for service sector', 'Margin money grant (subsidy) on the project cost'],
            [Language.HI]: ['उद्योगों के लिए ₹25 लाख तक का ऋण', 'सेवा क्षेत्र के लिए ₹10 लाख तक का ऋण', 'परियोजना लागत पर मार्जिन मनी अनुदान (सब्सिडी)'],
            [Language.TE]: ['పరిశ్రమలకు ₹25 లక్షల వరకు రుణం', 'సేవా రంగానికి ₹10 లక్షల వరకు రుణం', 'ప్రాజెక్ట్ వ్యయంపై మార్జిన్ మనీ గ్రాంట్ (సబ్సిడీ)'],
        },
        documents: {
            [Language.EN]: ['Domicile Certificate of UP', 'Aadhaar Card', 'Project Report', 'Educational Qualification Certificate'],
            [Language.HI]: ['यूपी का अधिवास प्रमाण पत्र', 'आधार कार्ड', 'परियोजना रिपोर्ट', 'शैक्षिक योग्यता प्रमाण पत्र'],
            [Language.TE]: ['యుపి నివాస ధృవీకరణ పత్రం', 'ఆధార్ కార్డ్', 'ప్రాజెక్ట్ నివేదిక', 'విద్యా అర్హత ధృవీకరణ పత్రం'],
        },
        applyLink: 'http://www.diupmsme.upsdc.gov.in/',
    },
    {
        id: 'pmfby',
        icon: 'leaf',
        name: {
            [Language.EN]: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
            [Language.HI]: 'प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाई)',
            [Language.TE]: 'ప్రధాన మంత్రి ఫసల్ బీమా యోజన (పిఎంఎఫ్‌బివై)',
        },
        description: {
            [Language.EN]: 'An insurance service for farmers for their yields. It provides a comprehensive insurance cover against failure of the crop thus helping in stabilising the income of the farmers.',
            [Language.HI]: 'किसानों को उनकी उपज के लिए एक बीमा सेवा। यह फसल की विफलता के खिलाफ एक व्यापक बीमा कवर प्रदान करता है जिससे किसानों की आय को स्थिर करने में मदद मिलती है।',
            [Language.TE]: 'రైతులకు వారి దిగుబడి కోసం ఒక భీమా సేవ. ఇది పంట వైఫల్యానికి వ్యతిరేకంగా ఒక సమగ్ర భీమా కవరేజీని అందిస్తుంది, తద్వారా రైతుల ఆదాయాన్ని స్థిరీకరించడంలో సహాయపడుతుంది.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 100,
            maxIncome: 10000000,
            states: ['Pan-India'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Farmer'],
        },
        benefits: {
            [Language.EN]: ['Insurance cover for crop loss due to natural calamities', 'Support for stabilising farm income', 'Encouragement for farmers to adopt innovative practices'],
            [Language.HI]: ['प्राकृतिक आपदाओं के कारण फसल हानि के लिए बीमा कवर', 'कृषि आय को स्थिर करने के लिए समर्थन', 'किसानों को नवीन प्रथाओं को अपनाने के लिए प्रोत्साहन'],
            [Language.TE]: ['ప్రకృతి వైపరీత్యాల వల్ల పంట నష్టానికి భీమా కవరేజ్', 'వ్యవసాయ ఆదాయాన్ని స్థిరీకరించడానికి మద్దతు', 'రైతులను వినూత్న పద్ధతులను అవలంబించడానికి ప్రోత్సాహం'],
        },
        documents: {
            [Language.EN]: ['Land records (RoR, Land possession Certificate)', 'Bank Passbook', 'Aadhaar Card'],
            [Language.HI]: ['भूमि रिकॉर्ड (आरओआर, भूमि कब्जा प्रमाण पत्र)', 'बैंक पासबुक', 'आधार कार्ड'],
            [Language.TE]: ['భూమి రికార్డులు (ఆర్‌ఓఆర్, భూమి స్వాధీన ధృవీకరణ పత్రం)', 'బ్యాంక్ పాస్‌బుక్', 'ఆధార్ కార్డ్'],
        },
        applyLink: 'https://pmfby.gov.in/',
    },
    {
        id: 'kanyashree-wb',
        icon: 'academic-cap',
        name: {
            [Language.EN]: 'Kanyashree Prakalpa (West Bengal)',
            [Language.HI]: 'कन्याश्री प्रकल्प (पश्चिम बंगाल)',
            [Language.TE]: 'కన్యాశ్రీ ప్రకల్ప (పశ్చిమ బెంగాల్)',
        },
        description: {
            [Language.EN]: 'A conditional cash transfer scheme to incentivize the schooling of teenage girls and prevent child marriage.',
            [Language.HI]: 'किशोरियों की स्कूली शिक्षा को प्रोत्साहित करने और बाल विवाह को रोकने के लिए एक सशर्त नकद हस्तांतरण योजना।',
            [Language.TE]: 'కౌమారదశలో ఉన్న బాలికల పాఠశాల విద్యను ప్రోత్సహించడానికి మరియు బాల్య వివాహాలను నివారించడానికి ఒక షరతులతో కూడిన నగదు బదిలీ పథకం.',
        },
        eligibility: {
            minAge: 13,
            maxAge: 18,
            maxIncome: 120000,
            states: ['West Bengal'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Student'],
            genders: ['Female'],
        },
        benefits: {
            [Language.EN]: ['Annual scholarship of Rs. 1000 for girls aged 13-18', 'One-time grant of Rs. 25,000 upon turning 18, if unmarried and in education'],
            [Language.HI]: ['13-18 आयु वर्ग की लड़कियों के लिए 1000 रुपये की वार्षिक छात्रवृत्ति', '18 वर्ष की होने पर 25,000 रुपये का एकमुश्त अनुदान, यदि अविवाहित और शिक्षा में हो'],
            [Language.TE]: ['13-18 సంవత్సరాల వయస్సు గల బాలికలకు రూ. 1000 వార్షిక స్కాలర్‌షిప్', '18 సంవత్సరాలు నిండిన తర్వాత రూ. 25,000 ఒకేసారి గ్రాంట్, అవివాహితులు మరియు విద్యలో ఉంటే'],
        },
        documents: {
            [Language.EN]: ['Birth Certificate', 'Unmarried Status Declaration', 'Proof of School Enrollment', 'Bank Account Details'],
            [Language.HI]: ['जन्म प्रमाण पत्र', 'अविवाहित स्थिति की घोषणा', 'स्कूल नामांकन का प्रमाण', 'बैंक खाता विवरण'],
            [Language.TE]: ['జనన ధృవీకరణ పత్రం', 'అవివాహిత స్థితి ప్రకటన', 'పాఠశాల నమోదు రుజువు', 'బ్యాంక్ ఖాతా వివరాలు'],
        },
        applyLink: 'https://www.wbkanyashree.gov.in/',
    },
    {
        id: 'cmes-mh',
        icon: 'light-bulb',
        name: {
            [Language.EN]: "Chief Minister's Entrepreneurship Scheme (Maharashtra)",
            [Language.HI]: 'मुख्यमंत्री उद्यमिता योजना (महाराष्ट्र)',
            [Language.TE]: 'ముఖ్యమంత్రి వ్యవస్థాపకత పథకం (మహారాష్ట్ర)',
        },
        description: {
            [Language.EN]: 'Financial assistance and support for first-generation entrepreneurs to set up new manufacturing and service enterprises in Maharashtra.',
            [Language.HI]: 'महाराष्ट्र में नई विनिर्माण और सेवा उद्यम स्थापित करने के लिए पहली पीढ़ी के उद्यमियों को वित्तीय सहायता और समर्थन।',
            [Language.TE]: 'మహారాష్ట్రలో కొత్త తయారీ మరియు సేవా సంస్థలను స్థాపించడానికి మొదటి తరం వ్యవస్థాపకులకు ఆర్థిక సహాయం మరియు మద్దతు.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 45,
            maxIncome: 800000,
            states: ['Maharashtra'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Entrepreneur'],
        },
        benefits: {
            [Language.EN]: ['Subsidized loans from banks', 'Government-backed credit guarantee', 'Skill development and mentorship programs'],
            [Language.HI]: ['बैंकों से रियायती ऋण', 'सरकार समर्थित क्रेडिट गारंटी', 'कौशल विकास और परामर्श कार्यक्रम'],
            [Language.TE]: ['బ్యాంకుల నుండి సబ్సిడీ రుణాలు', 'ప్రభుత్వ-మద్దతుగల క్రెడిట్ హామీ', 'నైపుణ్యాభివృద్ధి మరియు మార్గదర్శక కార్యక్రమాలు'],
        },
        documents: {
            [Language.EN]: ['Maharashtra Domicile Certificate', 'Detailed Project Report (DPR)', 'Aadhaar Card', 'PAN Card'],
            [Language.HI]: ['महाराष्ट्र अधिवास प्रमाण पत्र', 'विस्तृत परियोजना रिपोर्ट (डीपीआर)', 'आधार कार्ड', 'पैन कार्ड'],
            [Language.TE]: ['మహారాష్ట్ర నివాస ధృవీకరణ పత్రం', 'వివరణాత్మక ప్రాజెక్ట్ నివేదిక (డిపిఆర్)', 'ఆధార్ కార్డ్', 'పాన్ కార్డ్'],
        },
        applyLink: 'https://maitri.mahaonline.gov.in/',
    },
    {
        id: 'raitha-siri-ka',
        icon: 'leaf',
        name: {
            [Language.EN]: 'Raitha Siri Scheme (Karnataka)',
            [Language.HI]: 'रैथा सिरी योजना (कर्नाटक)',
            [Language.TE]: 'రైతు సిరి పథకం (కర్ణాటక)',
        },
        description: {
            [Language.EN]: 'A scheme to encourage farmers to cultivate millets by providing financial assistance, thereby promoting water conservation and healthy food.',
            [Language.HI]: 'किसानों को बाजरा की खेती के लिए प्रोत्साहित करने के लिए वित्तीय सहायता प्रदान करने की एक योजना, जिससे जल संरक्षण और स्वस्थ भोजन को बढ़ावा मिलता है।',
            [Language.TE]: 'రైతులను చిరుధాన్యాలు పండించడాన్ని ప్రోత్సహించడానికి ఆర్థిక సహాయం అందించే పథకం, తద్వారా నీటి సంరక్షణ మరియు ఆరోగ్యకరమైన ఆహారాన్ని ప్రోత్సహిస్తుంది.',
        },
        eligibility: {
            minAge: 18,
            maxAge: 100,
            maxIncome: 5000000,
            states: ['Karnataka'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Farmer'],
        },
        benefits: {
            [Language.EN]: ['Financial assistance of ₹10,000 per hectare for millet cultivation', 'Support for purchasing quality seeds', 'Market linkage support'],
            [Language.HI]: ['बाजरा की खेती के लिए प्रति हेक्टेयर ₹10,000 की वित्तीय सहायता', 'गुणवत्ता वाले बीज खरीदने के लिए समर्थन', 'बाजार लिंकेज समर्थन'],
            [Language.TE]: ['చిరుధాన్యాల సాగుకు హెక్టారుకు ₹10,000 ఆర్థిక సహాయం', 'నాణ్యమైన విత్తనాల కొనుగోలుకు మద్దతు', 'మార్కెట్ అనుసంధాన మద్దతు'],
        },
        documents: {
            [Language.EN]: ['Land records (RTC)', 'Aadhaar Card', 'Bank Passbook'],
            [Language.HI]: ['भूमि रिकॉर्ड (आरटीसी)', 'आधार कार्ड', 'बैंक पासबुक'],
            [Language.TE]: ['భూమి రికార్డులు (ఆర్‌టిసి)', 'ఆధార్ కార్డ్', 'బ్యాంక్ పాస్‌బుక్'],
        },
        applyLink: 'https://raitamitra.karnataka.gov.in/',
    },
    {
        id: 'bsby-rj',
        icon: 'shield-check',
        name: {
            [Language.EN]: 'Bhamashah Swasthya Bima Yojana (Rajasthan)',
            [Language.HI]: 'भामाशाह स्वास्थ्य बीमा योजना (राजस्थान)',
            [Language.TE]: 'భామాషా స్వాస్థ్య బీమా యోజన (రాజస్థాన్)',
        },
        description: {
            [Language.EN]: 'Provides cashless health insurance to eligible families in Rajasthan for IPD and specified day care procedures.',
            [Language.HI]: 'राजस्थान में पात्र परिवारों को आईपीडी और निर्दिष्ट डे केयर प्रक्रियाओं के लिए कैशलेस स्वास्थ्य बीमा प्रदान करता है।',
            [Language.TE]: 'రాజస్థాన్‌లోని అర్హతగల కుటుంబాలకు ఐపిడి మరియు నిర్దిష్ట డే కేర్ విధానాల కోసం నగదు రహిత ఆరోగ్య బీమాను అందిస్తుంది.',
        },
        eligibility: {
            minAge: 0,
            maxAge: 100,
            maxIncome: 250000,
            states: ['Rajasthan'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen', 'Farmer'],
        },
        benefits: {
            [Language.EN]: ['Cashless indoor patient services', 'Cover up to ₹3 lakh for critical illnesses', 'Includes pre and post hospitalization expenses'],
            [Language.HI]: ['कैशलेस इनडोर रोगी सेवाएं', 'गंभीर बीमारियों के लिए ₹3 लाख तक का कवर', 'अस्पताल में भर्ती होने से पहले और बाद के खर्च शामिल हैं'],
            [Language.TE]: ['నగదురహిత ఇండోర్ రోగి సేవలు', 'తీవ్రమైన అనారోగ్యాలకు ₹3 లక్షల వరకు కవరేజ్', 'ఆసుపత్రిలో చేరడానికి ముందు మరియు తరువాత ఖర్చులు ఉంటాయి'],
        },
        documents: {
            [Language.EN]: ['Bhamashah Card', 'Aadhaar Card', 'Ration Card'],
            [Language.HI]: ['भामाशाह कार्ड', 'आधार कार्ड', 'राशन कार्ड'],
            [Language.TE]: ['భామాషా కార్డ్', 'ఆధార్ కార్డ్', 'రేషన్ కార్డ్'],
        },
        applyLink: 'https://health.rajasthan.gov.in/mmnjym',
    },
    {
        id: 'kbf-kl',
        icon: 'gift',
        name: {
            [Language.EN]: 'Karunya Benevolent Fund (Kerala)',
            [Language.HI]: 'कारुण्य हितकारी निधि (केरल)',
            [Language.TE]: 'కారుణ్య దయగల నిధి (కేరళ)',
        },
        description: {
            [Language.EN]: 'Provides financial assistance to underprivileged people suffering from major illnesses like cancer, heart diseases, etc.',
            [Language.HI]: 'कैंसर, हृदय रोग आदि जैसी प्रमुख बीमारियों से पीड़ित वंचित लोगों को वित्तीय सहायता प्रदान करता है।',
            [Language.TE]: 'క్యాన్సర్, గుండె జబ్బులు మొదలైన ప్రధాన అనారోగ్యాలతో బాధపడుతున్న అణగారిన ప్రజలకు ఆర్థిక సహాయం అందిస్తుంది.',
        },
        eligibility: {
            minAge: 0,
            maxAge: 100,
            maxIncome: 300000,
            states: ['Kerala'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen'],
        },
        benefits: {
            [Language.EN]: ['Financial aid up to ₹2 lakh for critical diseases', 'Covers treatment costs for cancer, heart surgery, kidney and liver diseases'],
            [Language.HI]: ['गंभीर बीमारियों के लिए ₹2 लाख तक की वित्तीय सहायता', 'कैंसर, हृदय शल्य चिकित्सा, गुर्दे और यकृत रोगों के उपचार की लागत को कवर करता है'],
            [Language.TE]: ['తీవ్రమైన వ్యాధులకు ₹2 లక్షల వరకు ఆర్థిక సహాయం', 'క్యాన్సర్, గుండె శస్త్రచికిత్స, కిడ్నీ మరియు కాలేయ వ్యాధుల చికిత్స ఖర్చులను కవర్ చేస్తుంది'],
        },
        documents: {
            [Language.EN]: ['Aadhaar Card', 'Income Certificate', 'Medical Certificates from a Government Doctor'],
            [Language.HI]: ['आधार कार्ड', 'आय प्रमाण पत्र', 'सरकारी डॉक्टर से चिकित्सा प्रमाण पत्र'],
            [Language.TE]: ['ఆధార్ కార్డ్', 'ఆదాయ ధృవీకరణ పత్రం', 'ప్రభుత్వ వైద్యుడి నుండి వైద్య ధృవీకరణ పత్రాలు'],
        },
        applyLink: 'http://www.karunya.kerala.gov.in/',
    },
    {
        id: 'ma-yojana-gj',
        icon: 'shield-check',
        name: {
            [Language.EN]: 'Mukhyamantri Amrutum "MA" Yojana (Gujarat)',
            [Language.HI]: 'मुख्यमंत्री अमृतम "मा" योजना (गुजरात)',
            [Language.TE]: 'ముఖ్యమంత్రి అమృతం "మా" యోజన (గుజరాత్)',
        },
        description: {
            [Language.EN]: 'A health insurance scheme providing financial protection to Below Poverty Line (BPL) and lower-middle-class families in Gujarat against catastrophic health risks.',
            [Language.HI]: 'गुजरात में गरीबी रेखा से नीचे (बीपीएल) और निम्न-मध्यम-वर्गीय परिवारों को विनाशकारी स्वास्थ्य जोखिमों के खिलाफ वित्तीय सुरक्षा प्रदान करने वाली एक स्वास्थ्य बीमा योजना।',
            [Language.TE]: 'గుజరాత్‌లో దారిద్య్రరేఖకు దిగువన (బిపిఎల్) మరియు దిగువ-మధ్యతరగతి కుటుంబాలకు విపత్కర ఆరోగ్య నష్టాలకు వ్యతిరేకంగా ఆర్థిక రక్షణ కల్పించే ఆరోగ్య బీమా పథకం.',
        },
        eligibility: {
            minAge: 0,
            maxAge: 100,
            maxIncome: 400000,
            states: ['Gujarat'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Citizen'],
        },
        benefits: {
            [Language.EN]: ['Cashless quality medical and surgical treatment', 'Coverage up to ₹5,00,000 per family per year', 'Covers costs of diagnostics, surgery, medicines'],
            [Language.HI]: ['कैशलेस गुणवत्तापूर्ण चिकित्सा और सर्जिकल उपचार', 'प्रति परिवार प्रति वर्ष ₹5,00,000 तक का कवरेज', 'निदान, सर्जरी, दवाओं की लागत को कवर करता है'],
            [Language.TE]: ['నగదు రహిత నాణ్యమైన వైద్య మరియు శస్త్రచికిత్స చికిత్స', 'సంవత్సరానికి ప్రతి కుటుంబానికి ₹5,00,000 వరకు కవరేజ్', 'డయాగ్నస్టిక్స్, శస్త్రచికిత్స, மருந்துகల ఖర్చులను కవర్ చేస్తుంది'],
        },
        documents: {
            [Language.EN]: ['MA Card', 'Aadhaar Card', 'Income Certificate', 'Proof of Residence'],
            [Language.HI]: ['मा कार्ड', 'आधार कार्ड', 'आय प्रमाण पत्र', 'निवास का प्रमाण'],
            [Language.TE]: ['మా కార్డ్', 'ఆధార్ కార్డ్', 'ఆదాయ ధృవీకరణ పత్రం', 'నివాస రుజువు'],
        },
        applyLink: 'https://www.magujarat.com/',
    },
    {
        id: 'mkuy-br',
        icon: 'academic-cap',
        name: {
            [Language.EN]: 'Mukhyamantri Kanya Utthan Yojana (Bihar)',
            [Language.HI]: 'मुख्यमंत्री कन्या उत्थान योजना (बिहार)',
            [Language.TE]: 'ముఖ్యమంత్రి కన్య ఉత్థాన్ యోజన (బీహార్)',
        },
        description: {
            [Language.EN]: 'Promotes girls\' education and aims to curb child marriage by providing financial assistance from birth until graduation.',
            [Language.HI]: 'जन्म से लेकर स्नातक तक वित्तीय सहायता प्रदान करके लड़कियों की शिक्षा को बढ़ावा देता है और बाल विवाह पर अंकुश लगाने का लक्ष्य रखता है।',
            [Language.TE]: 'పుట్టినప్పటి నుండి గ్రాడ్యుయేషన్ వరకు ఆర్థిక సహాయం అందించడం ద్వారా బాలికల విద్యను ప్రోత్సహిస్తుంది మరియు బాల్య వివాహాలను అరికట్టడం లక్ష్యంగా పెట్టుకుంది.',
        },
        eligibility: {
            minAge: 0,
            maxAge: 25,
            maxIncome: 10000000,
            states: ['Bihar'],
            categories: ['General', 'SC', 'ST', 'OBC', 'EWS'],
            roles: ['Student'],
            genders: ['Female'],
        },
        benefits: {
            [Language.EN]: ['Financial aid at different stages of life', '₹25,000 on passing intermediate exams (unmarried)', '₹50,000 on completing graduation'],
            [Language.HI]: ['जीवन के विभिन्न चरणों में वित्तीय सहायता', 'इंटरमीडिएट परीक्षा पास करने पर ₹25,000 (अविवाहित)', 'स्नातक पूरा करने पर ₹50,000'],
            [Language.TE]: ['జీవితంలోని వివిధ దశలలో ఆర్థిక సహాయం', 'ఇంటర్మీడియట్ పరీక్షలలో ఉత్తీర్ణులైనప్పుడు ₹25,000 (అవివాహితులు)', 'గ్రాడ్యుయేషన్ పూర్తి చేసిన తర్వాత ₹50,000'],
        },
        documents: {
            [Language.EN]: ["Girl's Birth Certificate", 'Aadhaar Card', 'Bank Passbook', 'Educational certificates'],
            [Language.HI]: ['लड़की का जन्म प्रमाण पत्र', 'आधार कार्ड', 'बैंक पासबुक', 'शैक्षिक प्रमाण पत्र'],
            [Language.TE]: ['బాలిక జనన ధృవీకరణ పత్రం', 'ఆధార్ కార్డ్', 'బ్యాంక్ పాస్‌బుక్', 'విద్యా ధృవపత్రాలు'],
        },
        applyLink: 'https://ekalyan.bih.nic.in/',
    }
];