import React from 'react';
import { Scheme } from '../types';
// FIX: Use `useTranslation` hook to get the current language for consistency.
import { useTranslation } from '../hooks/useTranslation';
import Icon from './Icons';

interface SchemePrintLayoutProps {
    scheme: Scheme;
}

const PrintSection: React.FC<{ title: string; items: string[]; icon: string }> = ({ title, items, icon }) => (
    <div className="mb-6">
        <h3 className="text-lg font-bold text-gray-800 mb-2 pb-1 border-b-2 border-teal-500 flex items-center gap-2">
            <Icon icon={icon} className="w-5 h-5 text-teal-600" />
            {title}
        </h3>
        <ul className="list-disc list-inside space-y-1 text-gray-700 text-sm">
            {items.map((item, index) => <li key={index}>{item}</li>)}
        </ul>
    </div>
);

const SchemePrintLayout: React.FC<SchemePrintLayoutProps> = ({ scheme }) => {
    // FIX: Destructure `lang` from `useTranslation` hook, which provides it, instead of `useLanguage`.
    const { lang } = useTranslation();

    return (
        <div className="p-8 bg-white text-black">
            <header className="flex items-center justify-between pb-4 border-b border-gray-200">
                <div>
                    <h1 className="text-3xl font-extrabold text-gray-900">{scheme.name[lang]}</h1>
                    <p className="text-sm text-gray-500">Scheme Summary Document</p>
                </div>
                <div className="flex items-center gap-2 text-teal-600">
                    <Icon icon="shield-check" className="w-10 h-10" />
                    <span className="text-2xl font-bold">Yogyatha</span>
                </div>
            </header>
            
            <main className="mt-8">
                <section className="mb-6">
                    <h2 className="text-lg font-bold text-gray-800 mb-2">Scheme Overview</h2>
                    <p className="text-gray-700 text-sm leading-relaxed">{scheme.description[lang]}</p>
                </section>

                {scheme.easySummary?.[lang] && (
                    <section className="mb-6 p-4 bg-yellow-50 border-l-4 border-yellow-400 rounded-r-md">
                        <h3 className="font-bold text-yellow-800 text-base flex items-center gap-2">
                           <Icon icon="sparkles" className="w-5 h-5"/>
                           Simplified Summary
                        </h3>
                        <p className="text-yellow-700 text-sm mt-1">{scheme.easySummary[lang]}</p>
                    </section>
                )}
                
                <div className="grid grid-cols-2 gap-8">
                    <PrintSection title="Key Benefits" icon="gift" items={scheme.benefits[lang]} />
                    <PrintSection title="Required Documents" icon="document-text" items={scheme.documents[lang]} />
                </div>

                 <div className="mt-8 pt-4 border-t border-gray-200">
                    <h3 className="text-lg font-bold text-gray-800 mb-2">Application Link</h3>
                    <a href={scheme.applyLink} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm break-all">
                        {scheme.applyLink}
                    </a>
                </div>
            </main>
            
            <footer className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-500">
                <p>Generated by Yogyatha on {new Date().toLocaleDateString()}.</p>
                <p>Please verify all information on the official government website before applying.</p>
            </footer>
        </div>
    );
};

export default SchemePrintLayout;
